---
- hosts: 127.0.0.1
  connection: local
  sudo: true
  tasks:
    - name: php-cliインストール
      yum: name={{item}}
      with_items:
          - php-cli
          - bzip2-devel
          - re2c
          - libmhash
          - libicu
          - libicu-devel
          - libcurl

    - name: phpbrewインストール
      shell: curl -L -o /usr/local/bin/phpbrew https://github.com/phpbrew/phpbrew/raw/master/phpbrew && chmod +x /usr/local/bin/phpbrew
      remote_user: worker

    # - name: phpbrewセットアップ
    #   command: |
    #     phpbrew init
    #     export PHPBREW_ROOT=/opt/phpbrew
    #     source $HOME/.phpbrew/bashrc
    #     phpbrew install 5.6.3
    #     phpbrew switch 5.6.3
    #     sed -i "s/\;date\.timezone\ \=/date\.timezone\ \=\ Asia\/Tokyo/g" ~/.phpbrew/php/php-5.6.3/etc/php.ini
    #     phpbrew install-phpunit
    #     phpbrew install-composer
    #     echo "export PHPBREW_ROOT=/opt/phpbrew && source /opt/phpbrew/bashrc" > /etc/profile.d/phpbrew
    #   remote_user: worker
